//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRS.DeskApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\CRONOS PROJECT\\JATIS\\SUGAR LABINTA\\project\\SRS NEW\\SRS.DeskApp\\bin\\Debug\\app\\T" +
            "urn ON Led ADAM\\PTurnONLed.exe")]
        public string app_start_lamp {
            get {
                return ((string)(this["app_start_lamp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\CRONOS PROJECT\\JATIS\\SUGAR LABINTA\\project\\SRS NEW\\SRS.DeskApp\\bin\\Debug\\app\\O" +
            "pen Gate\\POpenGate.exe")]
        public string app_open_gate {
            get {
                return ((string)(this["app_open_gate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\CRONOS PROJECT\\JATIS\\SUGAR LABINTA\\project\\SRS NEW\\SRS.DeskApp\\bin\\Debug\\app\\\\" +
            "Open Gate\\POpenGate.exe")]
        public string app_close_gate {
            get {
                return ((string)(this["app_close_gate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\CRONOS PROJECT\\JATIS\\SUGAR LABINTA\\project\\SRS NEW\\SRS.DeskApp\\bin\\Debug\\app\\U" +
            "nloading\\PUnloading.exe")]
        public string app_unload {
            get {
                return ((string)(this["app_unload"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\PC-PC\\Export\\Place-1\\")]
        public string csv_file {
            get {
                return ((string)(this["csv_file"]));
            }
            set {
                this["csv_file"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\PC-PC\\Export\\Place-1\\")]
        public string csv_file_manual {
            get {
                return ((string)(this["csv_file_manual"]));
            }
            set {
                this["csv_file_manual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ip_core_sampling_line1 {
            get {
                return ((string)(this["ip_core_sampling_line1"]));
            }
            set {
                this["ip_core_sampling_line1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ip_core_sampling_line2 {
            get {
                return ((string)(this["ip_core_sampling_line2"]));
            }
            set {
                this["ip_core_sampling_line2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.50.221")]
        public string ip_gate1 {
            get {
                return ((string)(this["ip_gate1"]));
            }
            set {
                this["ip_gate1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.50.221")]
        public string ip_gate2 {
            get {
                return ((string)(this["ip_gate2"]));
            }
            set {
                this["ip_gate2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.102")]
        public string ip_gate3 {
            get {
                return ((string)(this["ip_gate3"]));
            }
            set {
                this["ip_gate3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.103")]
        public string ip_gate4 {
            get {
                return ((string)(this["ip_gate4"]));
            }
            set {
                this["ip_gate4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.104")]
        public string ip_gate5 {
            get {
                return ((string)(this["ip_gate5"]));
            }
            set {
                this["ip_gate5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.105")]
        public string ip_gate6 {
            get {
                return ((string)(this["ip_gate6"]));
            }
            set {
                this["ip_gate6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\CRONOS PROJECT\\JATIS\\SUGAR LABINTA\\project\\SRS NEW\\SRS.DeskApp\\bin\\Debug\\app\\")]
        public string externalAppPath {
            get {
                return ((string)(this["externalAppPath"]));
            }
            set {
                this["externalAppPath"] = value;
            }
        }
    }
}
