//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRS.DeskApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_config
    {
        public int device_id { get; set; }
        public string device_name { get; set; }
        public string device_ip { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string update_by { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string type_id { get; set; }
        public string fld_data_nir { get; set; }
        public string fld_data_manual { get; set; }
        public string ip_nir { get; set; }
        public string folder_nir { get; set; }
        public Nullable<int> print_max_count { get; set; }
        public Nullable<int> print_counter { get; set; }
    }
}
