//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRS.DeskApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_conf_acc
    {
        public int id { get; set; }
        public string inv_code { get; set; }
        public string cash_acc_no { get; set; }
        public string ar_acc_no { get; set; }
        public string ex_acc_no { get; set; }
        public string item_name { get; set; }
        public string kode_gudang { get; set; }
    }
}
