//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRS.DeskApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_list
    {
        public int ID { get; set; }
        public string kode_mitra { get; set; }
        public string nama_mitra { get; set; }
        public string ketua_kelompok { get; set; }
        public string nama_kelompok { get; set; }
        public string jenis_mitra { get; set; }
        public string alamat_ktp { get; set; }
        public string no_ktp { get; set; }
        public string no_hp { get; set; }
        public string no_kontrak { get; set; }
        public Nullable<System.DateTime> tgl_kontrak { get; set; }
        public Nullable<double> luas { get; set; }
        public string kategori { get; set; }
        public string varietas { get; set; }
        public Nullable<System.DateTime> tgl_tanam { get; set; }
        public string rayon { get; set; }
        public string penanggung_jawab { get; set; }
        public string koordinat_x { get; set; }
        public string koordinat_y { get; set; }
        public string kelurahan { get; set; }
        public string kecamatan { get; set; }
        public string kabupaten { get; set; }
        public string no_rek { get; set; }
        public string an_rek { get; set; }
        public string bank_rek { get; set; }
        public string kud { get; set; }
        public Nullable<System.DateTime> tgl_panen { get; set; }
        public Nullable<double> est_tch { get; set; }
        public Nullable<double> est_hasil_panen { get; set; }
        public string est_radius { get; set; }
        public Nullable<bool> reg_status { get; set; }
        public Nullable<int> est_ritase { get; set; }
        public string period_trx { get; set; }
    }
}
