//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRS.DeskApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_transit_scan_id_timbangan
    {
        public int doc_entry { get; set; }
        public int base_entry { get; set; }
        public string num_at_card { get; set; }
        public string car_id { get; set; }
        public string driver { get; set; }
        public string scan_in_ip_address { get; set; }
        public string scan_out_ip_address { get; set; }
        public Nullable<System.DateTime> date_in { get; set; }
        public Nullable<int> status_in { get; set; }
        public Nullable<int> status_out { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string update_by { get; set; }
        public Nullable<int> status_in2 { get; set; }
        public Nullable<int> status_out2 { get; set; }
    
        public virtual tbl_pendaftaran_mobil tbl_pendaftaran_mobil { get; set; }
    }
}
