//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRS.DeskApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kabupaten
    {
        public tbl_kabupaten()
        {
            this.tbl_kecamatan = new HashSet<tbl_kecamatan>();
        }
    
        public string kab_id { get; set; }
        public string kab_name { get; set; }
    
        public virtual ICollection<tbl_kecamatan> tbl_kecamatan { get; set; }
    }
}
