//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRS.DeskApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kecamatan
    {
        public tbl_kecamatan()
        {
            this.tbl_kelurahan = new HashSet<tbl_kelurahan>();
        }
    
        public string kab_id { get; set; }
        public string kec_id { get; set; }
        public string kec_name { get; set; }
    
        public virtual tbl_kabupaten tbl_kabupaten { get; set; }
        public virtual ICollection<tbl_kelurahan> tbl_kelurahan { get; set; }
    }
}
