//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRS.DeskApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTicketNo
    {
        public int AutoID { get; set; }
        public int TicketNo { get; set; }
        public System.DateTime Dt { get; set; }
        public string TicketNoID { get; set; }
    }
}
