//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRS.DeskApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaction
    {
        public int id { get; set; }
        public string TicketNo { get; set; }
        public string VehDocEntry { get; set; }
        public string TransitDocEntry { get; set; }
        public string NumAtCard { get; set; }
        public string WBInIP { get; set; }
        public string WBOutIp { get; set; }
        public Nullable<System.DateTime> DTIn { get; set; }
        public Nullable<System.DateTime> DTOut { get; set; }
        public Nullable<bool> Pending { get; set; }
        public Nullable<decimal> InWeight { get; set; }
        public Nullable<decimal> OutWeight { get; set; }
        public string VehNo { get; set; }
        public string Driver { get; set; }
        public string Product { get; set; }
    }
}
