//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRS.DeskApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiket_header
    {
        public int id { get; set; }
        public string file_excel { get; set; }
        public string upload_desc { get; set; }
        public Nullable<bool> upload_status { get; set; }
    }
}
