//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRS.DeskApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiket_history
    {
        public int ID { get; set; }
        public string NamaKUD { get; set; }
        public string NoTiket { get; set; }
        public string NamaPetani { get; set; }
        public string NamaPetani2 { get; set; }
        public string KodeRegister { get; set; }
        public string KodeRegister2 { get; set; }
        public string Alamat { get; set; }
        public string Alamat2 { get; set; }
        public string DibuatOleh { get; set; }
        public string DiserahkanOlehJabatan { get; set; }
        public string PenanggungJawab { get; set; }
        public string PenanggungJawabJabatan { get; set; }
        public string Driver { get; set; }
        public string NoTruck { get; set; }
        public Nullable<decimal> LuasLahan { get; set; }
        public string VarietasTebu { get; set; }
        public string LokasiDesa { get; set; }
        public string LokasiKec { get; set; }
        public string LokasiKab { get; set; }
        public string KodeMitra { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string CreateTerminal { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public string UpdateTerminal { get; set; }
        public Nullable<System.DateTime> tglTTA { get; set; }
        public Nullable<System.DateTime> tglKontrak { get; set; }
        public Nullable<decimal> EstBeratTebu { get; set; }
        public string KodeMitra2 { get; set; }
        public string kategori { get; set; }
        public Nullable<decimal> est_tch { get; set; }
        public Nullable<int> est_ritase { get; set; }
        public Nullable<decimal> est_hasil_panen { get; set; }
        public Nullable<int> est_radius { get; set; }
        public System.DateTime tgl_panen { get; set; }
        public string no_kontrak { get; set; }
        public Nullable<decimal> est_luas_panen { get; set; }
        public string rayon { get; set; }
        public Nullable<bool> id_status { get; set; }
        public Nullable<int> tiket_master_id { get; set; }
        public Nullable<int> id_ref { get; set; }
    }
}
