//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRS.DeskApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class trans_data_type
    {
        public trans_data_type()
        {
            this.trans_data_line = new HashSet<trans_data_line>();
            this.trans_data_header = new HashSet<trans_data_header>();
        }
    
        public int SeqNo { get; set; }
        public string type_id { get; set; }
        public string type_desc { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual ICollection<trans_data_line> trans_data_line { get; set; }
        public virtual ICollection<trans_data_header> trans_data_header { get; set; }
    }
}
