//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRS.DeskApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class trans_data_line
    {
        public System.Guid idx { get; set; }
        public string trans_id { get; set; }
        public string type_trans { get; set; }
        public Nullable<int> base_entry { get; set; }
        public Nullable<System.DateTime> date_issued { get; set; }
        public Nullable<decimal> debet { get; set; }
        public Nullable<decimal> credit { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<bool> status { get; set; }
        public string ref_notes { get; set; }
    
        public virtual trans_data_header trans_data_header { get; set; }
        public virtual trans_data_type trans_data_type { get; set; }
    }
}
