//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRS.DeskApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class trans_data_saldo
    {
        public string partner_id { get; set; }
        public Nullable<decimal> currentdr0 { get; set; }
        public Nullable<decimal> currentcr0 { get; set; }
        public Nullable<decimal> currentdr1 { get; set; }
        public Nullable<decimal> currentcr1 { get; set; }
        public Nullable<decimal> currentdr2 { get; set; }
        public Nullable<decimal> currentcr2 { get; set; }
        public Nullable<decimal> currentdr3 { get; set; }
        public Nullable<decimal> currentcr3 { get; set; }
        public Nullable<decimal> currentdr4 { get; set; }
        public Nullable<decimal> currentcr4 { get; set; }
        public Nullable<decimal> currentdr5 { get; set; }
        public Nullable<decimal> currentcr5 { get; set; }
        public Nullable<decimal> currentdr6 { get; set; }
        public Nullable<decimal> currentcr6 { get; set; }
        public Nullable<decimal> currentdr7 { get; set; }
        public Nullable<decimal> currentcr7 { get; set; }
        public Nullable<decimal> currentdr8 { get; set; }
        public Nullable<decimal> currentcr8 { get; set; }
        public Nullable<decimal> currentdr9 { get; set; }
        public Nullable<decimal> currentcr9 { get; set; }
        public Nullable<decimal> currentdr10 { get; set; }
        public Nullable<decimal> currentcr10 { get; set; }
        public Nullable<decimal> currentdr11 { get; set; }
        public Nullable<decimal> currentcr11 { get; set; }
        public Nullable<decimal> currentdr12 { get; set; }
        public Nullable<decimal> currentcr12 { get; set; }
        public Nullable<int> year_period { get; set; }
    }
}
