//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRS.DeskApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_master_menu
    {
        public byte[] timestamp { get; set; }
        public int menu_id { get; set; }
        public string name { get; set; }
        public string caption { get; set; }
        public Nullable<int> form_id { get; set; }
        public Nullable<byte> seq_level { get; set; }
        public Nullable<byte> menu_run { get; set; }
        public Nullable<int> parent { get; set; }
        public Nullable<bool> popup_menu { get; set; }
        public Nullable<int> module_id { get; set; }
        public string run_script { get; set; }
        public Nullable<byte> seq_order { get; set; }
        public string history_form { get; set; }
        public string history_view { get; set; }
    
        public virtual user_master_form user_master_form { get; set; }
        public virtual user_master_modules user_master_modules { get; set; }
    }
}
