//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRS.DeskApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_table
    {
        public int User_ID { get; set; }
        public string User_Name { get; set; }
        public string EmpID { get; set; }
        public Nullable<int> Group_User { get; set; }
        public string dept { get; set; }
        public string password { get; set; }
        public string employee { get; set; }
        public string Name_dept { get; set; }
        public Nullable<bool> closing_status { get; set; }
        public Nullable<bool> login_status { get; set; }
        public Nullable<bool> sql_user { get; set; }
    
        public virtual user_table_group user_table_group { get; set; }
    }
}
