//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRS.DeskApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_table_group
    {
        public user_table_group()
        {
            this.user_table = new HashSet<user_table>();
        }
    
        public int id { get; set; }
        public string Group_Name { get; set; }
        public Nullable<bool> default_delete { get; set; }
        public string sql_user { get; set; }
        public string sql_password { get; set; }
    
        public virtual ICollection<user_table> user_table { get; set; }
    }
}
