//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRS.DeskApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_access_list
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> form_id { get; set; }
        public Nullable<int> visible { get; set; }
    }
}
